<a href="https://colab.research.google.com/github/minstaar/Python-and-AI-Programming/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install numpy

In [ ]:
import numpy as np

print(np.__version__)

1.26.4


In [ ]:
import numpy as np

d = np.arange(12).reshape(3, 4)
print(d)
print(d.dtype)
print(d.ndim)
print(d.T)
print(d.size)
print(d.nbytes)
d.flat = 1
print(d)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
int64
2
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
12
96
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [ ]:
import numpy as np
import pandas as pd

A = np.array([1, 2, 3])

B = [[1, 2, 3],
 [4, 5, 6]]
B = pd.DataFrame(B)
print(B)
B = np.array(B)
print(B)


   0  1  2
0  1  2  3
1  4  5  6
[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np

A = np.arange(0, 5, 2)
print(A, A.ndim, A.shape)

print(type(A), A.dtype)
A.astype(float)

[0 2 4] 1 (3,)
<class 'numpy.ndarray'> int64


array([0., 2., 4.])

In [ ]:
import numpy as np

A = np.arange(24)

B = A.reshape(3, 4, 2)
print(B, B.shape)

C = A.reshape(6, -1, 4)
print(C, C.shape)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]] (3, 4, 2)
[[[ 0  1  2  3]]

 [[ 4  5  6  7]]

 [[ 8  9 10 11]]

 [[12 13 14 15]]

 [[16 17 18 19]]

 [[20 21 22 23]]] (6, 1, 4)


In [ ]:
import numpy as np

A = np.arange(12).reshape(3, 4)

B = A.flatten()
print(B, B.shape)

print(A)
print(A[::-1])
print(A[:,::-1])
print(A[::-1, ::-1])

print(A.transpose())
print(A.T)

[ 0  1  2  3  4  5  6  7  8  9 10 11] (12,)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]
[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]]
[[11 10  9  8]
 [ 7  6  5  4]
 [ 3  2  1  0]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [ ]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(np.vstack((A, B)))
print(np.row_stack((A, B)))
print(np.concatenate((A, B), axis = 0))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(np.hstack((A, B)))
print(np.column_stack((A, B)))
print(np.concatenate((A, B), axis = 1))

[[1 2 5 6]
 [3 4 7 8]]
[[1 2 5 6]
 [3 4 7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
import numpy as np

A = np.arange(12).reshape(3, 4)
print(A)

print(np.vsplit(A, 3))
print(np.split(A, 3, axis = 0))
print(A[0:1], A[1:2], A[2:])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
[[0 1 2 3]] [[4 5 6 7]] [[ 8  9 10 11]]


In [ ]:
import numpy as np

A = np.arange(12).reshape(3, 4)
print(A)

print(np.hsplit(A, 4))
print(np.split(A, 4, axis = 1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[array([[0],
       [4],
       [8]]), array([[1],
       [5],
       [9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]
[array([[0],
       [4],
       [8]]), array([[1],
       [5],
       [9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]


In [ ]:
i mport numpy as np

A = np.arange(16).reshape(4, 4)

print(A)
print(A[0:4, 0:4:2])
print(A[::, ::3])
print(A[::2])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  2]
 [ 4  6]
 [ 8 10]
 [12 14]]
[[ 0  3]
 [ 4  7]
 [ 8 11]
 [12 15]]
[[ 0  1  2  3]
 [ 8  9 10 11]]


In [2]:
import numpy as np

A = np.array([1, 2, 3, 4, 5, 6])
print(A > 2)
print(A[A>2])
print(A[A!=3])

[False False  True  True  True  True]
[3 4 5 6]
[1 2 4 5 6]
